name: Fetch Now Page
on:
  schedule:
    - cron: "* */4 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  fetch-now-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Now Page
        run: |
          curl --location --header "Authorization: Bearer ${{ secrets.OMG_TOKEN }}" \
            "https://api.omg.lol/address/${{ secrets.OMG_ADDR }}/now" | \
            jq -r .response.now.content > now.md
      - name: Commit Now Page
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'fetch /now page'
          file_pattern: 'now.md'

