name: Tempest Conditions
on:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  refresh-tempest:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Tempest API data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://swd.weatherflow.com/swd/rest/better_forecast?station_id=${{ secrets.TEMPEST_STATION }}&token=${{ secrets.TEMPEST_TOKEN }}&units_temp=f&units_wind=mph&units_pressure=inhg&units_precip-in&units_distance=mi
      - name: Trim JSON
        run: | 
          echo "conditions=$(jq '.current_conditions' \"$fetchApiData\")" >> "$GITHUB_ENV"

        
